name: Update images & gallery

on:
  push:
    paths:
      - 'images/**'
  pull_request:
    paths:
      - 'images/**'
  workflow_dispatch:

permissions:
  contents: write   # required to create branches / PRs / commit files

jobs:
  make-thumbs-and-update-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Run thumbnail + gallery update script
        run: |
          python scripts/update_gallery.py

      # Create a PR for any changes made by the script
      - name: Create Pull Request with changes (if any)
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(images): generate missing thumbnails and update gallery.json"
          branch: "auto/thumbs-update-${{ github.run_id }}"
          title: "[automated] Update thumbnails & gallery.json"
          body: "This PR was created automatically to add missing thumbnails and update images/gallery.json."
          labels: automated, images
