name: Update Gallery JSON

on:
  workflow_dispatch:  # manually triggered from GitHub UI

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run gallery update script
        run: python3 ../../scripts/update_gallery.py
