name: Update Gallery JSON

on:
  workflow_dispatch:

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Check repo structure (debug)
        run: |
          echo "Current working directory:"
          pwd
          echo "List files in repo root:"
          ls -R

      - name: Run gallery update script
        run: |
          python3 scripts/update_gallery.py
