name: Update Gallery JSON

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Debug directory structure
        run: |
          echo "Working directory is: $(pwd)"
          echo "Contents of current folder:"
          ls -R

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install Pillow

      - name: Run gallery update script
        run: python3 scripts/update_gallery.py

      - name: Commit and push updates (safe)
        run: |
          set -euo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "Git status (before):"
          git status --porcelain --untracked-files=all || true

          # Stage exactly the files we expect
          git add images/gallery.json || true
          git add images/*-thumb.jpg || true

          echo "Staged files:"
          git diff --staged --name-only || true

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update gallery.json and thumbnails (action)"
            git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          fi
