name: Update Gallery JSON

on:
  workflow_dispatch:  # manual trigger from GitHub Actions UI

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Debug directory structure
        run: |
          echo "Working directory is:"
          pwd
          echo "Contents of current folder:"
          ls -R

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install Pillow

      - name: Run gallery update script
        run: python3 scripts/update_gallery.py

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A images/
          git diff --cached --quiet || git commit -m "Update gallery.json and thumbnails"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main



